#!/usr/bin/env python

"""
This script allows you to download a YouTube video given its video ID.
"""

import argparse
import os

from yt_dlp import YoutubeDL


def download_youtube_video(video_id: str, output_path="./download") -> str:
    """
    Downloads a YouTube video given its video ID.

    Args:
        video_id (str): The ID of the YouTube video.
        output_path (str, optional): The path where the video will be saved.
            Defaults to "./download".

    Returns:
        None
    """
    url = f"https://www.youtube.com/watch?v={video_id}"
    ydl_opts = {
        "outtmpl": os.path.join(output_path, "%(title)s.%(ext)s"),
        "noplaylist": True,
        "age_limit": 99,
    }
    try:
        with YoutubeDL(ydl_opts) as ydl:
            info_dict = ydl.extract_info(url, download=True)
            video_title = info_dict.get("title", None)
            print(f"Video downloaded successfully: {video_title}")
    except Exception as e:  # pylint: disable=broad-except
        print(f"An error occurred: {e}")
    return url


def _main(args: argparse.Namespace) -> None:
    download_youtube_video(args.video_id, args.output_path)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Download a YouTube video.")
    parser.add_argument(
        "video_id",
        type=str,
        help="The ID of the YouTube video.",
    )
    parser.add_argument(
        "-o",
        "--output_path",
        type=str,
        default="./download",
        help="The path where the video will be saved."
        " Defaults to the './download' directory.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    _main(_parse_args())
