#!/bin/bash -ex

. "$(dirname "$0")/common"

date && time (
    cd "$ESRGAN_DIR" && \
        "$NCNN" \
            -i "$EXTRACTED_FRAMES" \
            -o "$ENHANCED_FRAMES" \
            -s "$SCALE" \
            -n "$MODEL"
) ; date
