#!/bin/bash -ex

. "$(dirname "$0")/common"

WORKDIR="$(dirname "$0")"

(
    cd "$WORKDIR" && \
        "$NCNN" \
            -i "$EXTRACTED_FRAMES" \
            -o "$ENHANCED_FRAMES" \
            -s "$SCALE" \
            -n "$MODEL"
)
